M48
; DRILL file {KiCad 9.0.4} date 2025-12-01T22:05:58-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-01T22:05:58-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X118.685Y-72.4
X123.535Y-72.4
T2
X118.385Y-69.37
X123.835Y-69.37
M30
